/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingsystemcrud_mari_kanepaul;

/**
 *
 * @author Kane
 */
public class MainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        addAccBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        viewAccBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        delAccBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(140, 150));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        addAccBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        addAccBtn.setForeground(new java.awt.Color(153, 153, 153));
        addAccBtn.setText("<html><center>Add/Update<br>Account</center></html>");
        addAccBtn.setBorderPainted(false);
        addAccBtn.setContentAreaFilled(false);
        addAccBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAccBtn.setDefaultCapable(false);
        addAccBtn.setFocusPainted(false);
        addAccBtn.addActionListener(this::addAccBtnActionPerformed);
        jPanel1.add(addAccBtn, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setPreferredSize(new java.awt.Dimension(140, 150));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        viewAccBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        viewAccBtn.setForeground(new java.awt.Color(153, 153, 153));
        viewAccBtn.setText("View Account");
        viewAccBtn.setBorderPainted(false);
        viewAccBtn.setContentAreaFilled(false);
        viewAccBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAccBtn.setDefaultCapable(false);
        viewAccBtn.setFocusPainted(false);
        viewAccBtn.addActionListener(this::viewAccBtnActionPerformed);
        jPanel2.add(viewAccBtn, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(140, 150));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        delAccBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        delAccBtn.setForeground(new java.awt.Color(153, 153, 153));
        delAccBtn.setText("Delete Account");
        delAccBtn.setBorderPainted(false);
        delAccBtn.setContentAreaFilled(false);
        delAccBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delAccBtn.setDefaultCapable(false);
        delAccBtn.setFocusPainted(false);
        delAccBtn.addActionListener(this::delAccBtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 32, 60, 33);
        jPanel3.add(delAccBtn, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        setSize(new java.awt.Dimension(420, 150));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccBtnActionPerformed
        new addorupdateframe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addAccBtnActionPerformed

    private void viewAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAccBtnActionPerformed
        new searchAccountFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewAccBtnActionPerformed

    private void delAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAccBtnActionPerformed
        new delAccountFrame().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_delAccBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAccBtn;
    private javax.swing.JButton delAccBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton viewAccBtn;
    // End of variables declaration//GEN-END:variables
}
