/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingsystemcrud_mari_kanepaul;

/**
 *
 * @author Kane
 */
public class MainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        viewAccBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        viewTransactionBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(140, 150));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        viewAccBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        viewAccBtn.setForeground(new java.awt.Color(153, 153, 153));
        viewAccBtn.setText("<html><center>View<br>Accounts</center></html>");
        viewAccBtn.setBorderPainted(false);
        viewAccBtn.setContentAreaFilled(false);
        viewAccBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAccBtn.setDefaultCapable(false);
        viewAccBtn.setFocusPainted(false);
        viewAccBtn.addActionListener(this::viewAccBtnActionPerformed);
        jPanel2.add(viewAccBtn, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(140, 150));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        viewTransactionBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        viewTransactionBtn.setForeground(new java.awt.Color(153, 153, 153));
        viewTransactionBtn.setText("<html><center>View<br>Transactions</center></html>");
        viewTransactionBtn.setBorderPainted(false);
        viewTransactionBtn.setContentAreaFilled(false);
        viewTransactionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTransactionBtn.setDefaultCapable(false);
        viewTransactionBtn.setFocusPainted(false);
        viewTransactionBtn.addActionListener(this::viewTransactionBtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 32, 60, 33);
        jPanel3.add(viewTransactionBtn, gridBagConstraints);

        getContentPane().add(jPanel3);

        jPanel1.setPreferredSize(new java.awt.Dimension(140, 150));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("<html><center>View<br>Customers</center></html>");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(420, 150));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAccBtnActionPerformed
        new ViewAllAccounts().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewAccBtnActionPerformed

    private void viewTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionBtnActionPerformed
        new delAccountFrame().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_viewTransactionBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CustomerFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton viewAccBtn;
    private javax.swing.JButton viewTransactionBtn;
    // End of variables declaration//GEN-END:variables
}
