/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingsystemcrud_mari_kanepaul;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Kane
 */
public class WithdrawFrame extends javax.swing.JFrame {
    
    private ViewAllAccounts mainGui;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WithdrawFrame.class.getName());
    
    /**
     * Creates new form WithdrawFrame
     */
    public WithdrawFrame(ViewAllAccounts mainGui, int accid) {
        initComponents();
        this.mainGui = mainGui;
        
        accIdField.setText(String.valueOf(accid));
    }

    public WithdrawFrame() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accIdField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        withdrawBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Withdraw");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Withdraw Transaction");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 60, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Account ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel3, gridBagConstraints);

        accIdField.setEditable(false);
        accIdField.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(accIdField, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Amount:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        amountField.setPreferredSize(new java.awt.Dimension(300, 30));
        amountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountFieldKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        getContentPane().add(amountField, gridBagConstraints);

        withdrawBtn.setText("Withdraw");
        withdrawBtn.addActionListener(this::withdrawBtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(60, 0, 0, 0);
        getContentPane().add(withdrawBtn, gridBagConstraints);

        setSize(new java.awt.Dimension(606, 357));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
    
     String amountStr = amountField.getText().trim();
    if (amountStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter an amount!");
        return;
    }

    try {
        int accid = Integer.parseInt(accIdField.getText());
        int amount = Integer.parseInt(amountStr);
        
        if (amount <= 0) {
            JOptionPane.showMessageDialog(this, "Amount must be positive!");
            return;
        }

        AccountDAO dao = new AccountDAO();
        // Using your updated joined query method
        AccountDetails details = dao.getAccountDetailsById(accid); 

        if (details != null) {
            if (details.getBalance() >= amount) {
                Long newBalance = details.getBalance() - amount;
                
                if (dao.updateAccountBalance(accid, newBalance)) {
                    Transaction transaction = new Transaction(accid, "Withdraw", amount, new java.util.Date());
                    new TransactionDAO().addTransaction(transaction);
                    
                    mainGui.refreshTable(); 
                    JOptionPane.showMessageDialog(this, "Withdrawal successful!");
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient balance! Available: " + details.getBalance());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Account not found!");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid number format!");
    }
            
    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void amountFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyTyped
    
        char c = evt.getKeyChar();
    
    if (!Character.isDigit(c)) {
        evt.consume();
    }    
    // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WithdrawFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accIdField;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton withdrawBtn;
    // End of variables declaration//GEN-END:variables
}
